### ISSUE TITLE
If file contains gene multiple times for a patient, only one exists after running tm2cbio

### ISSUE THREAD

**Issue by aderidder** [j-hudecek/tm2cbio#2]
For example, if my source file contains:

<table>
<tr><td>PATIENT ID</td><td>VALUE</td><td>LOG2E</td><td>ZSCORE</td><td>PROBE</td><td>GENE ID</td><td>GENE SYMBOL</td></tr>
<tr><td>HT29</td><td>1.20</td><td>1.01</td><td>0.045</td><td>A_23_P100935</td><td>23746</td><td>AIPL1</td></tr>
<tr><td>HT29</td><td>1.43</td><td>1.22</td><td>1.5</td><td>A_23_P100931</td><td>23746</td><td>AIPL1</td></tr>
</table>

after running tm2cbio, the output will only contain the second one.

Given that cBio expects only one, we may have to aggregate them?

**Comment by j-hudecek** [comment]
fixed in 01ee870b281f51853f7bfb20a95ebb169a7a5ae7
allows aggregation with average, geometrical average (for log scaled), first or last. By default it throws an error when this situation happens
