### ISSUE TITLE
Invalid number of fields in tab separated data_clinical.txt

### ISSUE THREAD

**Issue by jochemb** [j-hudecek/tm2cbio#5]
The data_clinical.txt file created does not have an equal number of tabs in every line.  It appears there are no tabs at all between the last non-empty field and the end of line. 

This issue raises errors in the validator.

**Comment by j-hudecek** [comment]
resolved in https://github.com/j-hudecek/tm2cbio/commit/226ea9bb7b51d0f8e3755f83708de7e465750b30
