### ISSUE TITLE
clinical data header issue

### ISSUE THREAD

**Issue by aderidder** [j-hudecek/tm2cbio#9]
I'm not 100% sure what's going on, but if my input clinical file contains:

> PATIENT_ID    RNAseq Illumina HiSeq2000\siNon-Targeting 1 RNAseq: Illumina HiSeq2000\siNon-targeting 1

This becomes

> # PATIENT_ID   SAMPLE_ID   siNon-Targeting_1   siNon-targeting_1
> # PATIENT_ID   SAMPLE_ID   RNAseq_Illumina_HiSeq2000/siNon-Targeting_1 RNAseq:_Illumina_HiSeq2000/siNon-targeting_1
> # STRING   STRING  STRING  STRING
> # 5    5   5   5
> 
> PATIENT_ID    SAMPLE_ID   siNon-Targeting_1   siNon-targeting_1

Even though I'll change the header anyway, apparently there is a bug here as the difference between:
RNAseq Illumina HiSeq2000\siNon-Targeting 1 
and
RNAseq: Illumina HiSeq2000\siNon-targeting 1
is a ":" and a capital T and the difference we end up with is just the capital T. cBioPortal will not upload this, as it considers them the same.

**Comment by j-hudecek** [comment]
I’ve fixed the case sensitivity in 21bd2fdb87f1e6b503740c0228bb9c8960889f46, but if two columns are exactly the same it will hit the same problem. Luckily there is the manual concept mapping:

clinical mapping concept to column name replace="duplicateConcePtWithCRaZyCase" SomethingElse

I think that’s the best way to handle it
